### ISSUE TITLE
uBlock Origin?

### ISSUE THREAD

**Issue by Darthagnon** [r57zone/ProtonShell#1]
Is it possible to implement uBlock Origin as an extension within ProtonShell? The internet is unusable without adblockers these days.

PS. ProtonShell should be compatible with Win7, provided Edge Webview2 v109 or earlier is installed.

**Comment by r57zone** [comment]
User scripts are supported, if ublock origin can be somehow adapted as userscript maybe it will work. ProtonShell is more for one site, in its own window, if you use one site you can hide some blocks in the user script.

It's great that it works on Windows 7, I like it better than 10.
